# fly.toml app configuration file generated for nose-goes on 2024-04-25T15:10:01-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nose-goes'
primary_region = 'iad'

[build]

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
